# Generated by Django 4.1.3 on 2022-12-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_product_created_product_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
